---
apiVersion: v1
kind: Secret
metadata: 
  name: {{ include "apps.name" .}}-secrets
type: Opaque
data:
  MONGO_DB_USERNAME: "{{.Values.mongopass.username | default "" | b64enc }}"
  MONGO_DB_PASSWORD: "{{.Values.mongopass.password | default "" | b64enc }}"
